### ISSUE TITLE
[9.0] [mrp_bom_structure_xlsx] error when product does not have internal reference

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/manufacture-reporting#24]
The error is:
`
cannot concatenate 'str' and 'bool' objects: (<type 'exceptions.TypeError'>, TypeError("cannot concatenate 'str' and 'bool' objects",), <traceback object at 0x7f300e81a170>)
`

**Comment by JordiBForgeFlow** [comment]
cc @mreficent

**Comment by LoisRForgeFlow** [comment]
Related PR merged
