### ISSUE TITLE
mrp_order_report_product_barcode & mrp_order_report_stock_location

### ISSUE THREAD

**Issue by max3903** [OCA/manufacture-reporting#41]
# Product Barcode on the Production Order Report

This module adds the product code or lot/serial number barcode on the production order report so that manufacturing users can scan barcodes.

## Configuration

* Check the configuration of your products to make sure:
  * the barcode field is set
  * the tracking is configured: No tracking, By Lot Number, By Serial Number
* Create a BOM using these products

## Usage

* Create a manufacturing order for the BOM created above
* Print the Production Order

# Stock Location on the Production Order Report

This module adds the stock location on the production order report so that manufacturing users know where to pick.

## Usage

* Create a manufacturing order
* Print the Production Order

**Comment by LoisRForgeFlow** [comment]
Proposal completed long time ago.
