### ISSUE TITLE
 BOM Structure to Excel .XLSX Export the error

### ISSUE THREAD

**Issue by hermitguo** [OCA/manufacture-reporting#45]
I installed it in the container.
My environment: centos7.4 + docker18.05 + odoo10 docker, I have the installation pip install pyeval.
but there was an error :  Uncaught ReferenceError:pyeval is not defined.

why?

**Comment by HviorForgeFlow** [comment]
Hi @eremiter could you add full error content? I can't reproduce your error neither figure out why

**Comment by hermitguo** [comment]
Hi, hveficent<mailto:notifications@github.com>,
sorry, busy recently.

  *   I solved the problem,https://stackoverflow.com/questions/44720758/uncaught-referenceerror-pyeval-is-not-defined


  *   I hope it's helpful

  *

________________________________
hermit

**Comment by MiquelRForgeFlow** [comment]
Then, you should close the issue :)
