### ISSUE TITLE
Question Export Flattened BOM to Excel

### ISSUE THREAD

**Issue by harshanis91** [OCA/manufacture-reporting#72]
Hello,

We have installed Export BOM structure to Excel by Eficent, Odoo Community Association (OCA)
When I try to export a BOM for a top part, system is showing an error. 

![image](https://user-images.githubusercontent.com/60201453/73011616-6f1b4380-3dc9-11ea-8881-f80b55909c76.png)

This works fine for a lower level parts. We Odoo 12 version
Can you please look into this? 

Thank you. Regards

**Comment by bodedra** [comment]
@harshanis91 Are you able to reproduce it runbot? If not, then it's problem in your environment.

**Comment by harshanis91** [comment]
Hi @bodedra , 

Where Do you want me to recreate in? Can you please send me the link. 
Thanks

**Comment by bodedra** [comment]
@harshanis91 You may go to the repository [https://github.com/OCA/manufacture-reporting](url). Find related module and open it.

You will see runbot button. Like

![Firefox_Screenshot_2020-01-25T06-37-59 040Z](https://user-images.githubusercontent.com/14229503/73117418-5ea2ce80-3f6b-11ea-8fb8-188bd018c286.png)

And follow your step and try to reproduce it.

**Comment by harshanis91** [comment]
![image](https://user-images.githubusercontent.com/60201453/73204773-6e99ea00-40f4-11ea-9437-cbe8b177af8a.png)

@bodedra  This the screen I see , but I don't see Flattened BOM in it. Do you have any idea why that is?

Appreciate your help. Thanks

**Comment by bodedra** [comment]
@harshanis91 take a long breath and review it again. Check module name one by one.

**Comment by harshanis91** [comment]
@bodedra What login credentials should I use and where can I find it?

**Comment by LoisRForgeFlow** [comment]
in runbot, the login is always "admin" and so is the password ("admin").

**Comment by LoisRForgeFlow** [comment]
@harshanis91 You can find useful information in the OCA website: https://odoo-community.org/page/review. I'm closing this issue, please reopen if you find a real issue, use the mailing lists for more generic questions.
