### ISSUE TITLE
14.0 mrp_flattened_bom_xlsx no option to print the report

### ISSUE THREAD

**Issue by tarbib** [OCA/manufacture-reporting#97]
module: mrp_flattened_bom_xlsx
version: 14.0

**Steps to reproduce**
- Install the module

**Current behavior**
No option to print the flattened bom
![image](https://user-images.githubusercontent.com/2255433/193771456-4123bc5d-3253-4553-8c35-dccb8321294a.png)

**Expected behavior**
I wish to see the option to export the flattened BoM 

Thanks 🙏

**Comment by riv-dmason** [comment]
I have installed the same version and can see the export flattened BoM option but it doesn't produce a download?
